services:
  - type: web
    name: fastapi
    runtime: docker
    plan: free
    repo: https://github.com/ralina1002/wrapped-gpt
    region: frankfurt
    branch: main
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    buildFilter:
      paths:
      - app/**

  